/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerlaufRouteImport } from './routes/verlauf'
import { Route as UebungenRouteImport } from './routes/uebungen'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as KoerperRouteImport } from './routes/koerper'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as EinstellungenRouteImport } from './routes/einstellungen'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JourneyWaehlenRouteImport } from './routes/journey.waehlen'

const VerlaufRoute = VerlaufRouteImport.update({
  id: '/verlauf',
  path: '/verlauf',
  getParentRoute: () => rootRouteImport,
} as any)
const UebungenRoute = UebungenRouteImport.update({
  id: '/uebungen',
  path: '/uebungen',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const KoerperRoute = KoerperRouteImport.update({
  id: '/koerper',
  path: '/koerper',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const EinstellungenRoute = EinstellungenRouteImport.update({
  id: '/einstellungen',
  path: '/einstellungen',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyWaehlenRoute = JourneyWaehlenRouteImport.update({
  id: '/waehlen',
  path: '/waehlen',
  getParentRoute: () => JourneyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/einstellungen': typeof EinstellungenRoute
  '/journey': typeof JourneyRouteWithChildren
  '/koerper': typeof KoerperRoute
  '/skills': typeof SkillsRoute
  '/uebungen': typeof UebungenRoute
  '/verlauf': typeof VerlaufRoute
  '/journey/waehlen': typeof JourneyWaehlenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/einstellungen': typeof EinstellungenRoute
  '/journey': typeof JourneyRouteWithChildren
  '/koerper': typeof KoerperRoute
  '/skills': typeof SkillsRoute
  '/uebungen': typeof UebungenRoute
  '/verlauf': typeof VerlaufRoute
  '/journey/waehlen': typeof JourneyWaehlenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/einstellungen': typeof EinstellungenRoute
  '/journey': typeof JourneyRouteWithChildren
  '/koerper': typeof KoerperRoute
  '/skills': typeof SkillsRoute
  '/uebungen': typeof UebungenRoute
  '/verlauf': typeof VerlaufRoute
  '/journey/waehlen': typeof JourneyWaehlenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/einstellungen'
    | '/journey'
    | '/koerper'
    | '/skills'
    | '/uebungen'
    | '/verlauf'
    | '/journey/waehlen'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/einstellungen'
    | '/journey'
    | '/koerper'
    | '/skills'
    | '/uebungen'
    | '/verlauf'
    | '/journey/waehlen'
  id:
    | '__root__'
    | '/'
    | '/einstellungen'
    | '/journey'
    | '/koerper'
    | '/skills'
    | '/uebungen'
    | '/verlauf'
    | '/journey/waehlen'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EinstellungenRoute: typeof EinstellungenRoute
  JourneyRoute: typeof JourneyRouteWithChildren
  KoerperRoute: typeof KoerperRoute
  SkillsRoute: typeof SkillsRoute
  UebungenRoute: typeof UebungenRoute
  VerlaufRoute: typeof VerlaufRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verlauf': {
      id: '/verlauf'
      path: '/verlauf'
      fullPath: '/verlauf'
      preLoaderRoute: typeof VerlaufRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uebungen': {
      id: '/uebungen'
      path: '/uebungen'
      fullPath: '/uebungen'
      preLoaderRoute: typeof UebungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/koerper': {
      id: '/koerper'
      path: '/koerper'
      fullPath: '/koerper'
      preLoaderRoute: typeof KoerperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/einstellungen': {
      id: '/einstellungen'
      path: '/einstellungen'
      fullPath: '/einstellungen'
      preLoaderRoute: typeof EinstellungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/waehlen': {
      id: '/journey/waehlen'
      path: '/waehlen'
      fullPath: '/journey/waehlen'
      preLoaderRoute: typeof JourneyWaehlenRouteImport
      parentRoute: typeof JourneyRoute
    }
  }
}

interface JourneyRouteChildren {
  JourneyWaehlenRoute: typeof JourneyWaehlenRoute
}

const JourneyRouteChildren: JourneyRouteChildren = {
  JourneyWaehlenRoute: JourneyWaehlenRoute,
}

const JourneyRouteWithChildren =
  JourneyRoute._addFileChildren(JourneyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EinstellungenRoute: EinstellungenRoute,
  JourneyRoute: JourneyRouteWithChildren,
  KoerperRoute: KoerperRoute,
  SkillsRoute: SkillsRoute,
  UebungenRoute: UebungenRoute,
  VerlaufRoute: VerlaufRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
